org: kurtgithub
app: aws-nest
service: aws-nest
custom:
  serverless-offline:
    httpPort: 3000

frameworkVersion: "3"

plugins:
 - serverless-plugin-typescript
 - serverless-plugin-optimize
 - serverless-offline

provider:
 name: aws
 runtime: nodejs18.x
 
package:
  individually: true

functions:
 main:
   handler: src/lambda.handler
   events:
     - http:
         method: any
         # path: /{any+}nvm list
         path: /{proxy+}
